// build.rs

use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

fn main() {
    // Cargo sets OUT_DIR to a build-specific scratch directory
    // (e.g. target/debug/build/<crate>-<hash>/out/). Anything written here
    // persists for the lifetime of the build and can be pulled into the crate
    // via include!().
    let out_dir = env::var("OUT_DIR").unwrap();

    // Destination for build-time generated code implementing the matrix-vector product.
    // This file is emitted into Cargo's OUT_DIR as `algorand_matrix.rs` and later
    // included in the crate to provide the optimized implementation.
    let dest = Path::new(&out_dir).join("algorand_matrix.rs");

    // Pre-allocate ~4 MB — enough to hold the full generated source without
    // reallocating as we push each row and value into the string.
    let mut src = String::with_capacity(4 * 1024 * 1024);

    // Define the file header comment
    src.push_str("// Auto-generated by build.rs — do not edit manually.\n");
    src.push_str("//\n");
    src.push_str("// The Algorand Sumhash512 matrix: an 8x1024 array of u64 values derived from\n");
    src.push_str("// SHAKE256(u=64, n=8, m=1024, seed=\"Algorand\"). Each row defines a set of\n");
    src.push_str("// 1024 weights; the compression function sums the weights at positions where\n");
    src.push_str("// the corresponding input bit is 1 (mod 2^64) to produce one output word.\n");
    src.push_str("// Verifiable against algorand/c-sumhash: src/algorand_matrix.h.\n");
    src.push_str("pub(crate) static ALGORAND_MATRIX: [[u64; 1024]; 8] = [\n");

    // Derive the 8×1024 matrix of u64 values from SHAKE256("Algorand").
    let matrix = derive_algorand_matrix();

    // Iterate over each element in the matrix
    for row in &matrix {
        src.push_str("    [\n");
        // Write 8 values per line, matching the layout of algorand_matrix.h
        // in the reference C implementation for easy cross-referencing.
        for chunk in row.chunks(8) {
            src.push_str("        ");
            for (i, val) in chunk.iter().enumerate() {
                write!(src, "0x{val:016x}").unwrap();
                if i + 1 < chunk.len() {
                    src.push_str(", ");
                }
            }
            src.push_str(",\n");
        }
        src.push_str("    ],\n");
    }
    src.push_str("];\n");

    fs::write(&dest, src).unwrap();

    // Tell Cargo to only re-run this build script if build.rs itself changes,
    // not on every incremental rebuild.
    println!("cargo:rerun-if-changed=build.rs");
}

// ── Minimal SHAKE256 (Keccak-f[1600]) ───────────────────────────────────────
//
// Rate for SHAKE256: 1600 − 2×256 = 1088 bits = 136 bytes.
const SHAKE256_STATE_WORDS: usize = 25;
const SHAKE256_RATE: usize = 136;

struct Shake256 {
    /// The 1600-bit (200-byte) Keccak-f[1600] permutation state, stored as 25 × u64 words/lanes.
    state: [u64; SHAKE256_STATE_WORDS],
    /// Input buffer accumulating bytes until a full 136-byte block is ready.
    buf: [u8; SHAKE256_RATE],
    /// Bytes written into `buf` since the last permutation. Resets to 0 each block.
    pos: usize,
    /// Set to `true` after `finalize_xof()`; guards against absorbing after squeezing has begun.
    squeezing: bool,
    /// Bytes consumed from the current output block. When it hits `SHAKE256_RATE`, the block
    /// is exhausted and the next permutation is triggered.
    squeeze_pos: usize,
}

impl Shake256 {
    fn new() -> Self {
        Self {
            state: [0u64; SHAKE256_STATE_WORDS],
            buf: [0u8; SHAKE256_RATE],
            pos: 0,
            squeezing: false,
            // Set to SHAKE256_RATE so the first squeeze call sees an exhausted
            // output block and triggers a permutation before reading any bytes.
            squeeze_pos: SHAKE256_RATE,
        }
    }
}

fn derive_algorand_matrix() -> [[u64; 1024]; 8] {
    todo!()
}
