// build.rs

use std::{env, fmt::Write, fs, path::Path};

include!("src/keccak.rs");

// Sumhash512 matrix parameters:
//
//   u = 64   — bits per output word (one u64 lane).
//   n = 8    — number of rows; n × u = 8 × 64 = 512-bit output (hence "Sumhash512").
//   m = 1024 — number of columns; the input block size in bits (128 bytes),
//              giving a 2:1 compression ratio (1024 bits → 512 bits) per block.
//
// All three are encoded as u16 little-endian. u16 is the smallest type that
// fits all values (m=1024 overflows u8), and a uniform type keeps the encoding
// consistent with the reference C implementation (uint16_t in c-sumhash).
//
// "Algorand" is the domain separation seed — it binds this matrix uniquely to
// Algorand's use of Sumhash512. Any other seed produces a different matrix that
// Algorand nodes would reject. Verifiable against algorand/c-sumhash.
fn derive_algorand_matrix() -> [[u64; 1024]; 8] {
    let mut shake = Shake256::new();
    shake.absorb(&64u16.to_le_bytes());    // u: bits per output word
    shake.absorb(&8u16.to_le_bytes());     // n: number of rows
    shake.absorb(&1024u16.to_le_bytes()); // m: number of columns
    shake.absorb(b"Algorand");            // domain separation seed
    shake.flip();

    // Squeeze 8 × 1024 little-endian u64 values row by row.
    let mut matrix = [[0u64; 1024]; 8];
    let mut buf = [0u8; 8];
    for row in matrix.iter_mut() {
        for entry in row.iter_mut() {
            shake.squeeze(&mut buf);
            *entry = u64::from_le_bytes(buf);
        }
    }
    matrix
}

fn main() {
    // Cargo sets OUT_DIR to a build-specific scratch directory
    // (e.g. target/debug/build/<crate>-<hash>/out/). Anything written here
    // persists for the lifetime of the build and can be pulled into the crate
    // via include!().
    let out_dir = env::var("OUT_DIR").unwrap();

    // Destination for build-time generated code implementing the matrix-vector product.
    // This file is emitted into Cargo's OUT_DIR as `algorand_matrix.rs` and later
    // included in the crate to provide the optimized implementation.
    let dest = Path::new(&out_dir).join("algorand_matrix.rs");

    // Pre-allocate ~4 MB — enough to hold the full generated source without
    // reallocating as we push each row and value into the string.
    let mut src = String::with_capacity(4 * 1024 * 1024);

    // Define the file header comment
    src.push_str("// Auto-generated by build.rs — do not edit manually.\n");
    src.push_str("//\n");
    src.push_str("// The Algorand Sumhash512 matrix: an 8x1024 array of u64 values derived from\n");
    src.push_str("// SHAKE256(u=64, n=8, m=1024, seed=\"Algorand\"). Each row defines a set of\n");
    src.push_str("// 1024 weights; the compression function sums the weights at positions where\n");
    src.push_str("// the corresponding input bit is 1 (mod 2^64) to produce one output word.\n");
    src.push_str("// Verifiable against algorand/c-sumhash: src/algorand_matrix.h.\n");
    src.push_str("pub(crate) static ALGORAND_MATRIX: [[u64; 1024]; 8] = [\n");

    // Derive the 8×1024 matrix of u64 values from SHAKE256("Algorand").
    let matrix = derive_algorand_matrix();

    // Iterate over each element in the matrix
    for row in &matrix {
        src.push_str("    [\n");
        // Write 8 values per line, matching the layout of algorand_matrix.h
        // in the reference C implementation for easy cross-referencing.
        for chunk in row.chunks(8) {
            src.push_str("        ");
            for (i, val) in chunk.iter().enumerate() {
                write!(src, "0x{val:016x}").unwrap();
                if i + 1 < chunk.len() {
                    src.push_str(", ");
                }
            }
            src.push_str(",\n");
        }
        src.push_str("    ],\n");
    }
    src.push_str("];\n");

    fs::write(&dest, src).unwrap();

    // Tell Cargo to only re-run this build script if build.rs itself changes,
    // not on every incremental rebuild.
    println!("cargo:rerun-if-changed=build.rs");
}

